workflows:
  ios-no-sign:
    name: iOS No Codesign
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get packages
        script: |
          set -e
          flutter pub get
      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS
        script: |
          set -e
          flutter build ios --no-codesign --release --no-pub
          APP_PATH=$(find build/ios -name "Runner.app" -type d | head -n 1)
          cd $(dirname "$APP_PATH")
          mkdir -p Payload && cp -r Runner.app Payload/
          zip -r "$CM_BUILD_DIR/Runner.ipa" Payload
    artifacts:
      - "*.ipa"