// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfh5Ui9Od_Vjd5v3yFN4FNH2kZqt8XBN4',
    appId: '1:741024709189:web:a904cb175956818a57012c',
    messagingSenderId: '741024709189',
    projectId: 'attendancesystem-dbbfa',
    authDomain: 'attendancesystem-dbbfa.firebaseapp.com',
    storageBucket: 'attendancesystem-dbbfa.firebasestorage.app',
    measurementId: 'G-S87PY0RCVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5LOer49ITBS93a096qBxv0C1i3S8HUU',
    appId: '1:741024709189:android:181e758f1174c6ac57012c',
    messagingSenderId: '741024709189',
    projectId: 'attendancesystem-dbbfa',
    storageBucket: 'attendancesystem-dbbfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYv_tbXDcc8-aXj4nd1aAbW_9BleDun4A',
    appId: '1:741024709189:ios:af2fa765c9daf01157012c',
    messagingSenderId: '741024709189',
    projectId: 'attendancesystem-dbbfa',
    storageBucket: 'attendancesystem-dbbfa.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYv_tbXDcc8-aXj4nd1aAbW_9BleDun4A',
    appId: '1:741024709189:ios:af2fa765c9daf01157012c',
    messagingSenderId: '741024709189',
    projectId: 'attendancesystem-dbbfa',
    storageBucket: 'attendancesystem-dbbfa.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfh5Ui9Od_Vjd5v3yFN4FNH2kZqt8XBN4',
    appId: '1:741024709189:web:1045df4a7781066b57012c',
    messagingSenderId: '741024709189',
    projectId: 'attendancesystem-dbbfa',
    authDomain: 'attendancesystem-dbbfa.firebaseapp.com',
    storageBucket: 'attendancesystem-dbbfa.firebasestorage.app',
    measurementId: 'G-L5LC9S7V6Z',
  );
}
